export const GET_LIST_POST = "GET_LIST_POST";
export const GET_LIST_POST_SUCCESS = "GET_LIST_POST_SUCCESS";

export const GET_LIST_PRODUCTS = "GET_LIST_POST";
export const GET_LIST_PRODUCTS_SUCCESS = "GET_LIST_POST_SUCCESS";

export const DETAIL_PRODUCTS = "DETAIL_PRODUCTS";
export const DETAIL_PRODUCTS_SUCCESS = "DETAIL_PRODUCTS_SUCCESS";
